### ISSUE TITLE
xp bar background not transparent

### ISSUE THREAD

**Issue by Mias15** [krishsharma0413/DiscordLevelingCard#5]
As shown in the screenshot the background of the xp bar is not transparent - bad if you have a light background. 
![image](https://user-images.githubusercontent.com/51890392/234089119-c72d7f8c-3085-4214-a7fe-9a36f7f9c84c.png)

**Comment by krishsharma0413** [comment]
I will look into this immediately

**Comment by krishsharma0413** [comment]
can you please provide more info? what was the code that you used? can you provide me the entire image rather than this selected screenshot.

**Comment by krishsharma0413** [comment]
[this commit](https://github.com/krishsharma0413/DiscordLevelingCard/commit/d6d5bf9ec7772eb5532e6cf6fe7b5be6a98dc2e7) should fix your issue.
If you think it really did then please close the issue yourself
