### ISSUE TITLE
0 xp still show the progressbar

### ISSUE THREAD

**Issue by Melmacker** [krishsharma0413/DiscordLevelingCard#9]
Whould it be possible to make a check if the xp is 0 and if it is, it should just hide (dont draw) the progressbar?
![image](https://github.com/krishsharma0413/DiscordLevelingCard/assets/92475829/b7e11502-fe71-43e7-842c-71e6903f345b)

**Comment by krishsharma0413** [comment]
That would definitely be possible.
I will update you when i am done adding this feature
Thanks

**Comment by krishsharma0413** [comment]
![card](https://github.com/krishsharma0413/DiscordLevelingCard/assets/77439837/7ef8da8a-359c-4b25-9a20-dd30168ead48)

if this fixes the issue then please close the issue yourself.

thanks for pointing this out

**Comment by Melmacker** [comment]
Thank you and yes that fixed the issue.
Keep up the good work :D
